### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by daninthemix** [xzn/d3d10-mmxlc#1]
Is there a release for this? Really want to use Reshade with MMX Legacy Collections but it crashes, so I've been looking for a D3D10 wrapper.

**Comment by xzn** [comment]
I've gotten around to put up a release here:

https://github.com/xzn/d3d10-mmxlc/releases/tag/v0.1.0

Sorry for the very late replay.


A few notes:
This is designed to use [slang-shaders](https://github.com/libretro/slang-shaders) from [RetroArch](https://www.retroarch.com/). Don't know how to be compatible with ReShade.

I originally intended to allow custom render resolution similar to GeDoSaTo but I couldn't get it to work. So ignore those lines in the .ini file for now.

**Comment by daninthemix** [comment]
![image](https://user-images.githubusercontent.com/1974239/61778881-8451ee00-adf7-11e9-99d8-7c2e81cdfb10.png)

This is what I get.

**Comment by daninthemix** [comment]
I'm so sorry - Steam was still downloading the damn thing! The game runs fine now!

How can I configure the shader (apply parameters etc)?

**Comment by xzn** [comment]
![image](https://user-images.githubusercontent.com/1617680/61785502-3383ca80-ade2-11e9-87a3-1cf6f058d39e.png)

Just open `interp-mod.ini` in notepad and edit it directly. Once you save the file, the mod should pick up the change automatically.

`interp` should be set to `true` as it fixes upscaling artifact.
`slang_shader` is for 2D games in the series.
`slang_shader_3d` is for the two 3D games, e.g. could be set to `slang-shaders/anti-aliasing/smaa.slangp` too for instance.

Rest aren't that useful. The custom resolution thing doesn't work for now as I couldn't get the viewport set up correctly..

**Comment by daninthemix** [comment]
Cool, but I mean the actual shader settings - like I use the Lottes one, it has parameters for curvature (I think resolution too?) etc - how do we apply those parameters?

**Comment by xzn** [comment]
Hmm, sorry that's not implemented yet.

(I assume you mean these parameters?)
![image](https://user-images.githubusercontent.com/1617680/61787040-5663ae00-ade5-11e9-8a4f-cc2173f997f4.png)

For now you could try copy those presets and the shader stages that they reference and modify them manually.

Will add a way to change these parameters from the mod in the next days.

**Comment by daninthemix** [comment]
Yeah that's what I mean. So if I just set the warpX and warpY in the slang file itself, that should do what I need?

Thanks

**Comment by xzn** [comment]
According to the source code of RetroArch, the first number after the param name is the initial value:
```glsl
#pragma parameter warpX "warpX" 0.031 0.0 0.125 0.01
#pragma parameter warpY "warpY" 0.041 0.0 0.125 0.01
```
So for `crt-lottes.slang` change `0.031` to some value between `0.0` and `0.125` for warpX, and change `0.041` for warpY.

I don't have hot-reloading for shader sources though so to apply the changes, change `slang_shader` in `interp-mod.ini` to something else, save the config file, wait for the mod to pick up the change, then change `slang_shader` back.

In any case, I may just implement setting the params in `interp-mod.ini` directly. Implementing a UI like in RetroArch is too much touble for now haha.

**Comment by daninthemix** [comment]
works perfectly. thanks :)
