### ISSUE TITLE
Doesn't work on all games

### ISSUE THREAD

**Issue by daninthemix** [xzn/d3d10-mmxlc#3]
So I checked out MMX4 on LC1 and these filters work.

I played the entire way through MMX5 on LC2 with these filters, no problem.

I go to play MMX6 and see it has the standard filter - so this hook doesn't appear to be working for MMX6 :(

**Comment by xzn** [comment]
Should be fixed in 0aa58c8.

Apparently I never checked X6 before and now I noticed that FMVs and some menu items are not filtered either. In any case I'll upload the binaries soon after some other changes.

**Comment by daninthemix** [comment]
eta on an updated binary? :)

**Comment by xzn** [comment]
Should work for now:

[dinput8.zip](https://github.com/xzn/d3d10-mmxlc/files/3461208/dinput8.zip)
(You can now set shaders for the SNES games and PS1 games separately. The `render_3d` options are not working and are disabled so just ignore them.)

Let me know if you have any issues.

**Comment by daninthemix** [comment]
Thankyou! Seems to work with X6. Going to do a complete playthrough over the weekend, will report any issues.

**Comment by daninthemix** [comment]
Worked great, did a complete playthrough.

Thanks!
