### ISSUE TITLE
Does not work in exclusive full screen mode at 1920x1080.

### ISSUE THREAD

**Issue by mdzapeer** [xzn/d3d10-mmxlc#4]
Does not work in exclusive full screen mode at 1920x1080, black screen for the loaded game. Its fine in windowed or borderless windowed. Can only hear audio, switching to windowed restores the game video screen.

**Comment by xzn** [comment]
Does this happens for all the games? I couldn't reproduce this for some reason. What's in your `interp-mod.ini`?

What's your graphics card btw?

**Comment by mdzapeer** [comment]
It was happening on all games, I have a 120 hz monitor but exclusive fullscreen runs at 60hz. Running a 980ti nvidia. It's working now....strange. I had fast vsync on and ultra frame latency enabled.  Attaching my `interp-mod.ini`. Tried reproducing the issue but unable to, had a windows update as well. Closing issue.
[interp-mod.zip](https://github.com/xzn/d3d10-mmxlc/files/4315015/interp-mod.zip)
